<?php
$pdo = new PDO('mysql:host=localhost;dbname=qnztnquh_uberhealth', 'qnztnquh_uberhdb', 'Uber@Health2026!');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$lessons = [

// ─── DEPRESSION ────────────────────────────────────────────────────────────
[
  'title' => 'Understanding Your Low Mood',
  'title_sw' => 'Kuelewa Huzuni Yako',
  'slug' => 'understanding-your-low-mood',
  'category' => 'depression',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 8,
  'thumbnail_emoji' => '🌧',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 1,
  'summary' => 'Learn what depression actually is, why it is not a character flaw, and how it affects your brain and body.',
  'summary_sw' => 'Jifunze maana halisi ya unyogovu, kwa nini si udhaifu wa tabia, na jinsi unavyoathiri akili na mwili wako.',
  'content' => "## What is depression?\n\nDepression is not sadness. Sadness is a normal human response to loss or disappointment. Depression is a medical condition that affects how your brain processes emotion, motivation, and energy. It can arrive without an obvious reason, and it does not leave just because you try harder.\n\n## What is happening in your brain\n\nWhen you are depressed, the parts of your brain that regulate mood are working differently. Neurotransmitters like serotonin, dopamine, and noradrenaline are out of balance. This is not a personal failure. It is biology.\n\nYou may notice:\n- Persistent low mood most of the day\n- Loss of interest in things that used to matter\n- Fatigue even after sleep\n- Difficulty concentrating or making decisions\n- Negative thoughts that feel absolutely true\n- Changes in appetite or weight\n\n## The cruel trick of depression\n\nDepression lies to you. It says things like *Nothing will ever get better*, *I am a burden*, *There is no point*. These thoughts feel like facts. They are symptoms.\n\nOne of the most important things you can do is learn to notice when a thought is coming from your depression rather than from reality.\n\n## You are not your depression\n\nYou are a person experiencing depression. That distinction matters. Depression affects what you can do right now. It does not define who you are or what you are capable of.\n\n## What helps\n\nEvidence shows that these approaches reliably reduce depression:\n- Behavioural activation: doing small meaningful activities even when motivation is absent\n- Cognitive restructuring: challenging the distorted thoughts depression produces\n- Sleep hygiene: protecting the sleep that depression disrupts\n- Social connection: even brief, low-effort contact with others\n- Physical movement: exercise is as effective as medication for mild-to-moderate depression\n- Professional therapy: CBT and IPT have strong evidence bases",
  'content_sw' => "## Unyogovu ni nini?\n\nUnyogovu si huzuni. Huzuni ni jibu la kawaida la binadamu kwa kupoteza au kukatishwa tamaa. Unyogovu ni hali ya kiafya inayoathiri jinsi ubongo wako unavyoshughulikia hisia, motisha, na nguvu.\n\n## Kinachoendelea kwenye ubongo wako\n\nUnapoumwa na unyogovu, sehemu za ubongo wako zinazodhibiti hisia zinafanya kazi tofauti. Hii si kushindwa kwako binafsi, ni biolojia.\n\n## Unasaidiwaje\n\nUthibitisho unaonyesha kwamba hizi zinasaidia: shughuli za tabia, kurekebisha mawazo, usingizi mzuri, miunganiko ya kijamii, na mazoezi ya mwili.",
  'key_takeaways' => json_encode(["Depression is a medical condition, not a weakness or character flaw.", "Your brain chemistry changes during depression, this is not your fault.", "Negative thoughts in depression are symptoms, not facts.", "Multiple evidence-based approaches exist and work.", "You are not your depression, it is something you are experiencing."]),
  'key_takeaways_sw' => json_encode(["Unyogovu ni hali ya kiafya, si udhaifu.", "Mabadiliko ya kemikali ya ubongo wakati wa unyogovu si kosa lako.", "Mawazo mabaya katika unyogovu ni dalili, si ukweli."]),
],

[
  'title' => 'Behavioural Activation: The Science of Doing',
  'title_sw' => 'Uanzishaji wa Tabia: Sayansi ya Kutenda',
  'slug' => 'behavioural-activation',
  'category' => 'depression',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 12,
  'thumbnail_emoji' => '🚶',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 2,
  'summary' => 'Break the depression-inactivity spiral by scheduling small, meaningful activities even when you do not feel like it.',
  'summary_sw' => 'Vunja mzunguko wa unyogovu-kutofanya kwa kupanga shughuli ndogo zenye maana, hata usipohisi hivyo.',
  'content' => "## The depression trap\n\nWhen you are depressed, you lose motivation. So you do less. Doing less means fewer moments of reward, connection, or accomplishment. This deepens the depression, which kills motivation further. It is a spiral.\n\nBehavioural activation (BA) is the most evidence-backed treatment component for depression. The core insight: you do not wait to feel motivated to act. You act, and the motivation follows.\n\n## Why this works\n\nYour brain's reward system responds to activity and achievement, even small ones. When you do a meaningful activity, even reluctantly, you give your brain the signals it needs to start recovering. Every action, however small, is a vote cast against depression.\n\n## The two types of activities that help\n\n**Pleasure activities** include things that used to bring you enjoyment: a short walk, listening to a specific song, calling one person.\n\n**Mastery activities** create a sense of accomplishment: washing dishes, replying to one message you have been putting off, making your bed.\n\n## How to do it\n\n**Start small.** Depression makes everything feel impossible. A 3-minute walk is not pathetic, it is evidence that you can act against your mood.\n\n**Schedule, do not decide.** Depression will talk you out of anything if you leave it open. Write it down: 10am, walk to the gate and back. Treat it like a medical appointment.\n\n**Rate your mood before and after.** Use a 0 to 10 scale. Most people notice even a small improvement. This is data. It teaches your brain that action shifts mood.\n\n**Build gradually.** Once you have a few activities in a week that reliably shift your mood, add another. Do not try to fill your whole week on day one.",
  'content_sw' => "## Mtego wa unyogovu\n\nUnyogovu unapoua motisha yako, unafanya kidogo. Kufanya kidogo kunamaanisha furaha na mafanikio kidogo zaidi. Hii inazidisha unyogovu zaidi.\n\nUanzishaji wa tabia ni matibabu bora zaidi ya unyogovu. Wazo kuu: haufanyi kazi ukiwa umengojea motisha. Unafanya kazi, na motisha inakuja baadaye.\n\n## Jinsi ya kufanya\n\nAnza kwa shughuli ndogo, tembea dakika tatu, osha vyombo, piga simu mtu mmoja. Panga wakati wake badala ya kuamua wakati huo. Pima hali yako kabla na baada.",
  'key_takeaways' => json_encode(["Action precedes motivation in depression, you do not wait to feel ready.", "Both pleasure and mastery activities fight depression effectively.", "Start with activities that take 2 to 5 minutes, size does not matter, momentum does.", "Schedule activities like appointments, depression will cancel anything left flexible.", "Even a 1-point mood improvement after an activity is evidence worth tracking."]),
  'key_takeaways_sw' => json_encode(["Hatua inakuja kabla ya motisha katika unyogovu.", "Anza na shughuli ndogo sana, dakika 2-5 inatosha.", "Panga shughuli kama miadi ya daktari."]),
],

[
  'title' => 'Challenging Negative Thought Patterns',
  'title_sw' => 'Kupinga Mifumo ya Mawazo Hasi',
  'slug' => 'challenging-negative-thoughts',
  'category' => 'depression',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 15,
  'thumbnail_emoji' => '🧠',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 3,
  'summary' => 'Identify the cognitive distortions depression produces and learn CBT techniques to reframe them.',
  'summary_sw' => 'Tambua upotofu wa mawazo unaozalishwa na unyogovu na ujifunze mbinu za CBT za kuyarekebisha.',
  'content' => "## Thoughts are not facts\n\nDepression creates predictable patterns of distorted thinking. These distortions feel completely true when you are in them. Learning to name them is the first step to losing their power over you.\n\n## The most common distortions in depression\n\n**All-or-nothing thinking**: I failed at one thing, so I am a complete failure. Reality check: almost nothing is all-or-nothing.\n\n**Catastrophising**: This problem will ruin everything forever. Reality check: what is the actual most likely outcome, not the worst imaginable?\n\n**Mind reading**: They think I am pathetic. Reality check: what evidence do you actually have for that?\n\n**Emotional reasoning**: I feel worthless, therefore I am worthless. Reality check: feelings are not measurements of reality.\n\n**Personalisation**: Everything went wrong because of me. Reality check: what other factors contributed?\n\n**Filtering**: You notice only what went wrong and screen out what went right.\n\n## The three-column technique\n\nWhen a painful thought arises, write three things:\n\n1. The automatic thought, exactly as it appeared\n2. The distortion, which pattern is this?\n3. The balanced response, what would a fair witness say?\n\nYou do not need to believe the balanced response immediately. Write it anyway. With repetition, it starts to feel more possible.\n\n## The friend test\n\nIf a close friend came to you with the same situation, what would you actually say to them? Most people are far kinder to others than to themselves. The friend test helps you access that kinder, more accurate voice.",
  'content_sw' => "## Mawazo si ukweli\n\nUnyogovu unazalisha mifumo ya kawaida ya mawazo ya upotofu. Kujifunza kuyataja ni hatua ya kwanza.\n\n## Upotofu wa kawaida\n\nFikira ya kila kitu au hakuna kitu, kutarajia mbaya zaidi, kusoma mawazo ya wengine, kuhisi kwa sababu unafikiri.\n\n## Mbinu ya safu tatu\n\nWaandike fikira ya moja kwa moja, aina ya upotofu, na jibu la usawa. Fanya hivi mara kwa mara.",
  'key_takeaways' => json_encode(["Depression produces predictable thought distortions. Learning to name them weakens them.", "The most common are: all-or-nothing, catastrophising, mind reading, emotional reasoning, personalisation, filtering.", "The three-column technique is the core CBT exercise for negative thoughts.", "You do not need to believe the balanced response immediately. Writing it still helps.", "The friend test reveals the kinder, more accurate voice you rarely use on yourself."]),
  'key_takeaways_sw' => json_encode(["Unyogovu unazalisha upotofu wa mawazo unaotarajiwa.", "Jifunza kuyataja: yote au chochote, kutarajia mbaya, kusoma mawazo.", "Mbinu ya safu tatu inasaidia kurekebisha mawazo."]),
],

[
  'title' => 'Sleep and Depression: Breaking the Cycle',
  'title_sw' => 'Usingizi na Unyogovu: Kuvunja Mzunguko',
  'slug' => 'sleep-and-depression',
  'category' => 'depression',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 10,
  'thumbnail_emoji' => '🌙',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 4,
  'summary' => 'Depression wrecks sleep, and poor sleep worsens depression. Learn the evidence-based techniques to reclaim your rest.',
  'summary_sw' => 'Unyogovu unaharibu usingizi, na usingizi mbaya unazidisha unyogovu. Jifunza mbinu za kupata pumziko lako.',
  'content' => "## The sleep-depression cycle\n\nDepression disrupts sleep in two main ways: it either causes insomnia or hypersomnia. Both make the depression worse. Poor sleep reduces the brain's ability to regulate emotion, increases negative thinking, and kills motivation.\n\n## What actually works\n\n**Fix your wake time first.** Choose a consistent wake time and keep it even on weekends, even if you had a bad night. This anchors your circadian rhythm.\n\n**Get bright light in the morning.** Within 30 minutes of waking, expose yourself to bright natural light. This is the strongest signal your brain has to calibrate its clock and lift daytime mood.\n\n**Do not lie in bed awake.** If you cannot sleep after 20 minutes, get up and do something quiet. Return to bed when sleepy. This prevents your brain from associating bed with wakefulness and anxiety.\n\n**Cut the phone an hour before bed.** The blue light from screens suppresses melatonin. More importantly, checking social media activates the anxiety circuits you need to quiet.\n\n**Wind-down ritual.** A consistent ritual of 10 minutes, such as herbal tea, stretching, or gratitude notes, trains the nervous system to transition into sleep.\n\n**Limit daytime naps.** If you must nap, keep it to 20 minutes before 2pm.\n\n## For hypersomnia (sleeping too much)\n\nSleeping 12 to 16 hours does not mean you are getting more rest. In depression it usually increases fatigue and isolation. Use behavioural activation to create reasons to get up.",
  'content_sw' => "## Mzunguko wa usingizi na unyogovu\n\nUnyogovu huharibu usingizi, na usingizi mbaya huzidisha unyogovu. Mzunguko huu unaweza kuvunjwa.\n\n## Kinachofanya kazi kweli kweli\n\nWeka wakati wa kuamka mapema hata wikendi. Pata mwanga mkali asubuhi. Usikae kitandani ukiwa macho. Punguza simu saa moja kabla ya kulala. Fanya utaratibu wa kupumzika.",
  'key_takeaways' => json_encode(["Depression disrupts sleep both ways, insomnia and hypersomnia both worsen the condition.", "Fix your wake time first, it is the strongest lever for stabilising your sleep cycle.", "Morning bright light is the most powerful signal to calibrate your brain's clock.", "Do not lie in bed awake, get up after 20 minutes and return when sleepy.", "A consistent wind-down ritual trains your nervous system to transition to sleep."]),
  'key_takeaways_sw' => json_encode(["Weka wakati wa kuamka unaofanana kila siku.", "Mwanga wa asubuhi ni muhimu kwa mzunguko wako wa saa.", "Usikae kitandani ukiwa macho zaidi ya dakika 20."]),
],

[
  'title' => 'Building a Depression Safety Net',
  'title_sw' => 'Kujenga Wavu wa Usalama wa Unyogovu',
  'slug' => 'depression-safety-net',
  'category' => 'depression',
  'language' => 'en',
  'level' => 'advanced',
  'duration_minutes' => 14,
  'thumbnail_emoji' => '🕸',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 5,
  'summary' => 'Build a personalised relapse prevention plan with warning signs, coping strategies, and who to call, before you need it.',
  'summary_sw' => 'Jenga mpango wa kuzuia kurudi kwa unyogovu na dalili za onyo, mikakati ya kukabiliana, na nani wa kupigia simu.',
  'content' => "## Why prevention matters\n\nDepression often follows a pattern. There are early warning signs that appear days or weeks before a full episode. Most people can learn to recognise their own pattern and take action early, when it is much easier.\n\n## Step 1: Know your personal warning signs\n\nCommon warning signs include: withdrawing from people without explaining why, stopping self-care basics, ruminating more than usual, losing interest in your most important values, sleeping much more or less than normal, and negative thoughts becoming more frequent.\n\nWrite down your 3 to 5 most reliable warning signs.\n\n## Step 2: Your Tier 1 responses (early signs)\n\nWhen you notice 1 to 2 warning signs, take these actions immediately: contact your therapist, schedule one behavioural activation activity per day for the next week, tell one trusted person that you are noticing something.\n\n## Step 3: Your Tier 2 responses (episode beginning)\n\nIf the episode is deepening: request an urgent session with your therapist, activate your support network honestly, reduce commitments where possible, consider whether medication should be reviewed.\n\n## Step 4: Your support people\n\nName 2 to 3 people who know about your depression and who you trust to take you seriously. For each one, write their name, their relationship to you, and what you have agreed they can do when you are struggling.\n\n## Step 5: Crisis numbers\n\nKeep a crisis line number somewhere you will find it even in a very dark moment. The SOS button on this platform connects you to a counsellor at any time. Befrienders Kenya: 0722 178 177.\n\n## The key principle\n\nYour safety net only works if it exists before the crisis. Build it now.",
  'content_sw' => "## Kwa nini kuzuia kunasaidia\n\nUnyogovu mara nyingi hufuata mfumo. Kuna dalili za mapema kabla ya kipindi kamili.\n\n## Hatua muhimu\n\n1. Jua dalili zako za onyo za kibinafsi\n2. Jibu la haraka unapoziona\n3. Watu wanaokusaidia, majina na nambari\n4. Nambari za dharura",
  'key_takeaways' => json_encode(["Depression often follows a pattern. Learning yours lets you intervene early.", "Write down your personal 3 to 5 warning signs before you need them.", "Create two tiers of response: early signs vs episode beginning.", "Name 2 to 3 trusted people and agree in advance what they can do.", "Your safety net must be built when you are well, depression will not let you build it in a crisis."]),
  'key_takeaways_sw' => json_encode(["Jifunza ishara zako za mapema za unyogovu.", "Weka mpango wa hatua mbili: mapema na kipindi kinachokua.", "Taja watu wanaokuamini 2-3 kabla ya dharura."]),
],

// ─── ANXIETY ───────────────────────────────────────────────────────────────
[
  'title' => 'What Is Your Anxiety Telling You?',
  'title_sw' => 'Wasiwasi Wako Unakuambia Nini?',
  'slug' => 'what-is-anxiety-telling-you',
  'category' => 'anxiety',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 8,
  'thumbnail_emoji' => '⚡',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 1,
  'summary' => 'Understand anxiety as your brain\'s alarm system, and why it sometimes fires when there is no real danger.',
  'summary_sw' => 'Elewa wasiwasi kama mfumo wa kengele wa ubongo wako na kwa nini wakati mwingine unapiga kelele bila hatari halisi.',
  'content' => "## Anxiety is not your enemy\n\nAnxiety is your brain doing its job. The fear response evolved over millions of years to protect you from danger. When you are genuinely threatened, anxiety sharpens your senses, floods you with adrenaline, and prepares your body to fight or flee. This system saves lives.\n\nThe problem is that this same system can misfire. In modern life, it activates in response to job interviews, relationship conflicts, and messages. Things that feel threatening but do not require physical escape.\n\n## What happens in your body\n\nWhen anxiety activates:\n- Heart rate increases to pump blood to muscles\n- Breathing quickens to take in more oxygen\n- Muscles tense ready to act\n- Digestion slows as a non-essential function\n- Attention narrows to the perceived threat\n\nNone of this is dangerous. It is uncomfortable when it happens in response to something that does not require physical action.\n\n## Why anxiety becomes a problem\n\nAnxiety becomes problematic when it activates too frequently, too intensely, or when you start avoiding situations to prevent it and the avoidance grows.\n\n## The avoidance trap\n\nAvoidance is the main thing that maintains anxiety. When you avoid something that triggered anxiety, you feel relief. Your brain registers this as confirmation that the thing was truly dangerous. Next time, the anxiety fires earlier and louder. Every avoided situation makes anxiety stronger.\n\n## What helps anxiety\n\n- Breathing techniques to regulate the physical response\n- Grounding to bring attention back from future threat to present moment\n- Worry containment to reduce free-floating anxiety\n- Gradual exposure, the systematic facing of avoided situations\n- Cognitive techniques to challenge overestimates of danger",
  'content_sw' => "## Wasiwasi si adui yako\n\nWasiwasi ni ubongo wako ukifanya kazi yake. Mfumo wa hofu ulibadilika kwa mamilioni ya miaka ili kukuepusha na hatari. Tatizo ni kwamba mfumo huo unaweza kupiga kengele bila sababu halisi.\n\n## Kinachosaidia\n\nMbinu za kupumua, kuthibitisha, muda wa wasiwasi, na kukabiliana na hali polepole kunasaidia wasiwasi.",
  'key_takeaways' => json_encode(["Anxiety is your brain's threat-detection system, it evolved to protect you.", "The physical symptoms of anxiety are not dangerous.", "Avoidance is the main thing that keeps anxiety alive, facing fears reduces it.", "Anxiety overestimates danger and underestimates your ability to cope.", "Treatment works by gradually facing feared situations, not by eliminating all discomfort."]),
  'key_takeaways_sw' => json_encode(["Wasiwasi ni mfumo wa kengele wa ubongo, umebadilika kulinda.", "Kuepuka kunaimarisha wasiwasi, kukabiliana kunaupunguza.", "Wasiwasi unazidisha hatari na kupunguza uwezo wako wa kukabiliana."]),
],

[
  'title' => 'The 4-7-8 Breathing Technique',
  'title_sw' => 'Mbinu ya Kupumua 4-7-8',
  'slug' => '4-7-8-breathing',
  'category' => 'anxiety',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 7,
  'thumbnail_emoji' => '🫁',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 2,
  'summary' => 'Use controlled breathing to activate your parasympathetic nervous system and lower anxiety within minutes.',
  'summary_sw' => 'Tumia kupumua kwa udhibiti kuamsha mfumo wako wa neva na kupunguza wasiwasi ndani ya dakika chache.',
  'content' => "## Why breathing works\n\nYour breathing is the one part of your autonomic nervous system you can consciously control. When you slow and extend your exhale, you directly activate the parasympathetic system, the body's natural off switch for the fight-or-flight response.\n\nThis is not relaxation advice. This is physiology. A long exhale literally lowers your heart rate and cortisol.\n\n## The 4-7-8 technique\n\nThe pattern:\n1. Inhale through your nose for 4 counts\n2. Hold for 7 counts\n3. Exhale slowly through your mouth for 8 counts\n4. Repeat 4 times\n\nThe key is the extended exhale. The 8-count exhale is what activates the parasympathetic response. If 4-7-8 feels too long at first, try 4-4-6 and build up.\n\n## When to use it\n\n- Before a feared situation such as a job interview or difficult conversation\n- During an anxiety spike when you feel the physical symptoms ramping up\n- Before sleep when anxious thoughts are racing\n- Any moment when you notice your body tensing\n\n## Practise when calm\n\nThe technique works better when you have practised it during calm moments. Your body learns the pattern. When anxiety strikes and your thinking narrows, your body knows what to do.\n\nPractise once in the morning and once before sleep for two weeks.\n\n## The physiological sigh\n\nFor the most immediate effect: two quick inhales through the nose, then one long exhale through the mouth. This deflates the alveoli in your lungs and is the fastest way to reduce physiological arousal.",
  'content_sw' => "## Kwa nini kupumua kunafanya kazi\n\nKupumua kwako ni sehemu moja ya mfumo wako wa neva unaofahamu kudhibitiwa. Unapopunguza na kupanua kuvuta pumzi yako, unaanzisha moja kwa moja mfumo wa parasympathetic.\n\n## Mbinu ya 4-7-8\n\n1. Vuta pumzi kwa pua kwa hesabu 4\n2. Shikilia kwa hesabu 7\n3. Toa pumzi polepole kwa mdomo kwa hesabu 8\n4. Rudia mara 4",
  'key_takeaways' => json_encode(["A long exhale directly activates the parasympathetic system, this is physiology not just relaxation.", "The 4-7-8 pattern is among the most studied breathing interventions for anxiety.", "Practise it when calm so it works automatically under stress.", "For immediate effect, the physiological sigh (two quick inhales, one long exhale) works fastest.", "Use it before feared situations, during anxiety spikes, and before sleep."]),
  'key_takeaways_sw' => json_encode(["Kuvuta pumzi ndefu kunaanzisha mfumo wa kupumzika, hii ni fiziolojia.", "Fanya mazoezi ukiwa na utulivu ili mwili wako ujifunze mfumo.", "Tumia kabla ya hali zinazoogopa, wakati wa wasiwasi mkali, na kabla ya kulala."]),
],

[
  'title' => 'Grounding: The 5-4-3-2-1 Method',
  'title_sw' => 'Kuthibitisha: Mbinu ya 5-4-3-2-1',
  'slug' => 'grounding-54321',
  'category' => 'anxiety',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 6,
  'thumbnail_emoji' => '🌱',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 3,
  'summary' => 'Pull yourself out of anxious spirals by anchoring your attention to the present through your five senses.',
  'summary_sw' => 'Jitoe kwenye mizunguko ya wasiwasi kwa kumfunga mawazo yako sasa hivi kupitia hisi zako tano.',
  'content' => "## When anxiety pulls you out of the present\n\nAnxiety lives in the future. It asks: what if this goes wrong? What if I cannot cope? When you are anxious, your mind leaves the present moment and runs threat-simulation scenarios on a loop.\n\nGrounding breaks this loop by forcing your attention back to the present moment.\n\n## The 5-4-3-2-1 method\n\nWork slowly through each sense. Take a breath between each item.\n\n**5 things you can SEE.** Look around and name 5 things in your environment. Be specific: not just a chair but a blue plastic chair with a mark on the armrest.\n\n**4 things you can TOUCH.** Reach out and touch 4 surfaces or objects. Notice their texture, temperature, weight. The floor under your feet counts.\n\n**3 things you can HEAR.** Listen carefully and name 3 sounds. Include background sounds you normally filter out: traffic, aircon, your own breathing.\n\n**2 things you can SMELL.** What scents are in the air?\n\n**1 thing you can TASTE.** What taste is in your mouth right now?\n\n## Why it works\n\nYour sensory systems only register the present moment. They cannot perceive the future. When you deliberately engage them, you pull your nervous system into the present, and anxiety cannot sustain itself in the present moment.\n\n## When to use it\n\n- Panic attacks and high anxiety moments\n- Flashbacks (also used for PTSD)\n- Before important events when you feel spiralling\n- When overthinking is taking over\n\n## Physical anchors\n\nSome people find that cold water on the wrists or face, or a strong smell like coffee or citrus, are even faster anchors. Keep one of these in your toolkit.",
  'content_sw' => "## Kuthibitisha kuvunja mzunguko wa wasiwasi\n\nWasiwasi unaishi katika siku zijazo. Kuthibitisha kunalazimisha mawazo yako kurudi sasa hivi.\n\n## Mbinu ya 5-4-3-2-1\n\n- Vitu 5 unavyoweza KUONA\n- Vitu 4 unavyoweza KUGUSA\n- Vitu 3 unavyoweza KUSIKIA\n- Vitu 2 unavyoweza KUNUSA\n- Kitu 1 unachoweza KUONJA",
  'key_takeaways' => json_encode(["Anxiety lives in the future. Grounding pulls you back to the present moment.", "The 5-4-3-2-1 method uses your senses to anchor attention to what is actually happening now.", "Sensory systems only register the present. Anxiety cannot sustain itself here.", "Useful for panic attacks, flashbacks, overthinking spirals, and pre-event anxiety.", "Physical anchors (cold water, strong smell) can be even faster for very high anxiety."]),
  'key_takeaways_sw' => json_encode(["Wasiwasi unaishi katika siku zijazo, kuthibitisha kunarudi sasa hivi.", "Mfumo wa 5-4-3-2-1 unatumia hisi zako kufunga mawazo.", "Tumia kwa mashambulizi ya hofu, mawazo ya kurudi, na wasiwasi mkali."]),
],

[
  'title' => 'Worry Time: Containing Your Anxiety',
  'title_sw' => 'Muda wa Wasiwasi: Kudhibiti Wasiwasi Wako',
  'slug' => 'worry-time',
  'category' => 'anxiety',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 10,
  'thumbnail_emoji' => '🕐',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 4,
  'summary' => 'Schedule a daily worry window to contain free-floating anxiety and reclaim the rest of your day.',
  'summary_sw' => 'Panga dirisha la wasiwasi la kila siku ili kudhibiti wasiwasi unaoelea huru na kupata siku yako iliyobaki.',
  'content' => "## The problem with suppressing worry\n\nTelling yourself to stop worrying usually does not work. Thought suppression actually increases the frequency and intensity of those thoughts. Worry time works differently. Instead of suppressing worry, you contain it.\n\n## How worry time works\n\n**Step 1: Set a daily worry window.** Choose a 20 to 30 minute slot at a consistent time, not too close to bedtime. This is your designated time to worry. All other times are out of bounds.\n\n**Step 2: When a worry arises outside the window.** Do not engage with it. Instead, notice it, name it briefly, write it in a notebook, and gently redirect your attention to what you were doing. You are not suppressing, you are postponing.\n\n**Step 3: During your worry window.** Sit down and open your list. For each worry, ask: Is this something I can do something about right now? If yes, what one small action can I take? If no, acknowledge it and let it go.\n\nMost worries, when you finally sit with them, either resolve or reveal themselves as hypothetical and unanswerable.\n\n## Why it works\n\nContaining worry to a specific time reduces its grip on the rest of your day. You are not dismissing your concerns, you are managing when you engage with them. Over time, many people find their worry list shrinks.\n\n## The anxiety journal\n\nSome people keep a worry journal and notice patterns. The same worries appear over and over, peaking at certain times or in response to specific triggers. This pattern recognition shows you where your anxiety is focused.",
  'content_sw' => "## Tatizo la kukandamiza wasiwasi\n\nKujisemea acha kuwa na wasiwasi mara nyingi hakufanyi kazi. Muda wa wasiwasi unafanya kazi tofauti, badala ya kukandamiza wasiwasi, unaudhibiti.\n\n## Jinsi inavyofanya kazi\n\n1. Weka dirisha la wasiwasi la dakika 20-30 kila siku\n2. Wasiwasi unaotokea nje ya muda huu, uandike na uendelee\n3. Wakati wa dirisha lako, shughulikia kila wasiwasi moja kwa moja",
  'key_takeaways' => json_encode(["Suppressing worry increases it. Containment works better.", "Set a daily 20 to 30 minute worry window at a consistent time, not close to bedtime.", "When worry arises outside the window: name it, note it, postpone it. Do not engage.", "During the window: sort worries into actionable vs hypothetical.", "Most worries when examined directly are either solvable with a small action or unanswerable hypotheticals."]),
  'key_takeaways_sw' => json_encode(["Kukandamiza wasiwasi kunauimarisha, kudhibiti kunafanya kazi vizuri zaidi.", "Weka muda maalum wa wasiwasi wa dakika 20-30 kila siku.", "Wasiwasi unaotokea nje ya muda huu, uandike na uendelee na kazi yako."]),
],

[
  'title' => 'Facing Fears: The Exposure Ladder',
  'title_sw' => 'Kukabiliana na Hofu: Ngazi ya Mfiduo',
  'slug' => 'exposure-ladder',
  'category' => 'anxiety',
  'language' => 'en',
  'level' => 'advanced',
  'duration_minutes' => 18,
  'thumbnail_emoji' => '🪜',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 5,
  'summary' => 'Systematically reduce anxiety by building a graded exposure hierarchy and working through it one step at a time.',
  'summary_sw' => 'Punguza wasiwasi kwa njia ya mfumo kwa kujenga safu ya mfiduo iliyopangwa na kuifanyia kazi hatua moja kwa wakati.',
  'content' => "## Why avoidance must end\n\nEvery time you avoid something that triggers anxiety, you get short-term relief but long-term worsening. The avoided situation becomes more threatening in your mind. Gradually the avoidance expands, more things get avoided, life gets smaller.\n\nExposure is the most evidence-based treatment for anxiety disorders. By staying in a feared situation without the catastrophe happening, your brain learns the situation is not actually dangerous.\n\n## Building your exposure ladder\n\n**Step 1: Name your feared situation.** Be specific. Not social anxiety but speaking up in a work meeting.\n\n**Step 2: Rate the top of the ladder.** The most feared version gets a distress rating of 100.\n\n**Step 3: Build the ladder.** List 8 to 10 steps between doing nothing (rating 0) and facing the most feared situation (rating 100).\n\nExample ladder for social anxiety at meetings:\n- Rating 10: Attend a meeting and stay silent\n- Rating 20: Ask one clarifying question\n- Rating 35: Offer one comment on someone else's idea\n- Rating 50: Share an update about your work\n- Rating 65: Disagree with a point respectfully\n- Rating 80: Present a brief summary to the group\n- Rating 100: Lead a meeting\n\n**Step 4: Start at a rating 30 to 40 step.** Not the bottom (too easy, no learning) and not the top (too overwhelming).\n\n**Step 5: Stay in the situation until anxiety drops by at least half.** Do not leave at peak anxiety. Stay. The anxiety will peak and then naturally reduce. This usually takes 20 to 45 minutes.\n\n**Step 6: Repeat the same step until distress drops below 30.** Only then move to the next step up.\n\n## What to expect\n\nThe first exposure to a step is the hardest. The second is easier. By the third or fourth, most people report the step barely triggers anxiety. This is your brain learning.",
  'content_sw' => "## Kwa nini kuepuka lazima kuishie\n\nKila wakati unapoepuka kitu kinachozalisha wasiwasi, unapata faraja ya muda mfupi lakini kuzorota kwa muda mrefu.\n\n## Kujenga ngazi yako ya mfiduo\n\n1. Taja hali unayoiogopa\n2. Orodhesha hatua 8-10 kutoka kwa rahisi hadi ngumu\n3. Anza kwa hatua ya kati\n4. Kaa katika hali hiyo mpaka wasiwasi upungue nusu\n5. Rudia mpaka uwe rahisi, kisha panda hatua inayofuata",
  'key_takeaways' => json_encode(["Avoidance maintains anxiety. Exposure reduces it.", "Build a ladder of 8 to 10 steps from easiest to hardest.", "Start at a mid-level step, not the bottom and not the top.", "Stay in the feared situation until anxiety drops by at least 50%. Leaving at peak reinforces avoidance.", "Repeat each step until distress is below 30 before moving up the ladder."]),
  'key_takeaways_sw' => json_encode(["Kuepuka kunadumisha wasiwasi, mfiduo unaufundisha ubongo wako.", "Anza kwa hatua ya kati ya ngazi yako.", "Kaa katika hali unayoiogopa mpaka wasiwasi upungue nusu."]),
],

// ─── GAMBLING ──────────────────────────────────────────────────────────────
[
  'title' => 'Understanding the Gambling Urge',
  'title_sw' => 'Kuelewa Hamu ya Kucheza Kamari',
  'slug' => 'understanding-the-gambling-urge',
  'category' => 'gambling',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 10,
  'thumbnail_emoji' => '🎰',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 1,
  'summary' => 'Understand what drives gambling urges at the neurological level and why willpower alone is not enough to stop them.',
  'summary_sw' => 'Elewa kinachosababisha hamu ya kucheza kamari kwa kiwango cha neva na kwa nini nguvu ya mapenzi peke yake haitoshi.',
  'content' => "## Problem gambling is not a moral failure\n\nProblem gambling is a recognised condition driven by the same brain mechanisms as other addictions. People from all backgrounds develop it. Understanding the biology does not remove your responsibility, but it does remove the shame, and shame is one of the biggest barriers to recovery.\n\n## What happens in your brain\n\nGambling hijacks the dopamine reward system. The specific mechanism is variable ratio reinforcement: gambling pays out on an unpredictable schedule. Not every time, not never, but sometimes, in a pattern you cannot predict. Neuroscience shows this is the most addictive pattern possible. Betting apps and casino games are deliberately designed around it.\n\n**Near misses**: when you almost win, your brain fires dopamine as if you had won. This is a loss your brain misregisters as almost-winning.\n\n**Anticipation is the driver**: dopamine peaks not when you receive a reward but when you anticipate one. This is why the experience of placing a bet feels compelling even before any result.\n\n## The loss-chasing trap\n\nAfter a loss, the brain registers a deficit and urges you to restore it. Chasing by continuing to bet to recover losses feels rational. It is not. Each bet is independent. The previous loss does not change the odds. Chasing escalates losses and is one of the most dangerous patterns in problem gambling.\n\n## The urge is not a command\n\nAn urge is a signal your brain sends, not an instruction you must obey. Urges have a shape: they build, peak, and pass. They typically last 15 to 30 minutes at their most intense. If you can outlast the urge without acting on it, it will pass.",
  'content_sw' => "## Kamari si kushindwa kwa maadili\n\nKamari ya tatizo ni hali inayotambuliwa inayoendeshwa na taratibu sawa za ubongo kama madawa mengine. Kuelewa biolojia haziondoi jukumu lako, lakini inaondoa aibu.\n\n## Kinachoendelea kwenye ubongo wako\n\nKamari inaibia mfumo wa tuzo wa dopamine. Variable ratio reinforcement ni mfumo unaolevya zaidi. Near misses zinasababisha ubongo kufanya kama umeshinda.",
  'key_takeaways' => json_encode(["Problem gambling is driven by brain mechanisms, it is not a moral failure.", "Variable ratio reinforcement (unpredictable payouts) is the most addictive pattern possible.", "Near misses fire dopamine as if you won. They are losses your brain misregisters.", "Dopamine peaks during anticipation. The urge to bet is itself the high.", "Urges build, peak, and pass in 15 to 30 minutes. You do not have to act on them."]),
  'key_takeaways_sw' => json_encode(["Kamari ya tatizo ni tatizo la ubongo, si kushindwa kwa maadili.", "Variable ratio reinforcement ni mfumo unaolevya zaidi.", "Hamu zinajenga, kufikia kilele, na kupita ndani ya dakika 15-30."]),
],

[
  'title' => 'Identifying Your Gambling Triggers',
  'title_sw' => 'Kutambua Visababishi Vyako vya Kamari',
  'slug' => 'gambling-triggers',
  'category' => 'gambling',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 12,
  'thumbnail_emoji' => '🎯',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 2,
  'summary' => 'Map the people, places, emotions, and times that reliably trigger your gambling urges so you can plan around them.',
  'summary_sw' => 'Weka ramani ya watu, maeneo, hisia, na nyakati zinazosababisha hamu yako ya kucheza kamari ili uweze kupanga kuzunguka.',
  'content' => "## Why triggers matter\n\nRecovery from gambling does not happen through willpower in the moment. It happens through planning before the moment. If you know what triggers your urges, you can avoid high-risk situations, create barriers, and plan specific responses before you need them.\n\n## The four categories of triggers\n\n**External triggers** include places near a betting shop, technology such as apps on your phone and sports notifications, people you used to bet with, payday when money is available, and sport events.\n\n**Emotional triggers** include stress and anxiety, boredom, loneliness, excitement-seeking, low mood, and even celebration.\n\n**Thought triggers** include: I can control it this time, just one bet, I know this team will win, I am owed a win, no one will know.\n\n**Situational triggers** include unstructured time such as evenings and weekends, after a major stressor, and after even moderate alcohol use which lowers inhibitions.\n\n## Building your trigger map\n\nFor each trigger, write:\n1. The trigger as specifically as possible\n2. What you usually do, your typical response\n3. What you will do instead, a specific pre-planned alternative\n\n## The 15-minute rule\n\nFor any trigger that creates an urge, do anything else for 15 minutes. Call someone from your support network. Go for a walk. Make a meal. The urge will peak within that time and then decrease. You outlast it.",
  'content_sw' => "## Kwa nini visababishi ni muhimu\n\nKupona kutoka kwa kamari hakutokei kwa nguvu ya mapenzi wakati huo. Inatokea kwa kupanga kabla ya wakati huo.\n\n## Aina nne za visababishi\n\n- Vya nje: maeneo, teknolojia, watu, siku ya malipo\n- Vya kihisia: msongo, uchovu, upweke, kutafuta msisimko\n- Vya mawazo: ninaweza kudhibiti wakati huu, bet moja tu\n- Vya hali: wakati usiopangwa, baada ya stres kubwa",
  'key_takeaways' => json_encode(["Recovery happens through planning before urge moments, not willpower during them.", "Triggers fall into four categories: external, emotional, thought-based, and situational.", "Map your specific triggers and write a pre-planned alternative response for each.", "Technology triggers like apps and notifications should be removed permanently, not just managed.", "The 15-minute rule: do anything else for 15 minutes and the urge will peak and decrease."]),
  'key_takeaways_sw' => json_encode(["Kupona kunatokea kwa kupanga kabla, si nguvu ya mapenzi wakati wa hamu.", "Visababishi vina aina nne: vya nje, vya kihisia, vya mawazo, vya hali.", "Sheria ya dakika 15: fanya kitu chochote kingine kwa dakika 15."]),
],

[
  'title' => 'Urge Surfing: Riding Out the Wave',
  'title_sw' => 'Kusafiri kwenye Wimbi la Hamu',
  'slug' => 'urge-surfing-gambling',
  'category' => 'gambling',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 11,
  'thumbnail_emoji' => '🌊',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 3,
  'summary' => 'Use mindful observation to ride out gambling urges without acting on them, letting them rise, peak, and pass.',
  'summary_sw' => 'Tumia uchunguzi wa akili makini kupanda hamu ya kamari bila kutenda juu yake, kuziacha ziinuke, zifikilie kilele, na zipite.',
  'content' => "## What is urge surfing?\n\nUrge surfing is a mindfulness-based technique. Instead of fighting an urge or giving in to it, you observe it, watching it rise, peak, and pass, as a surfer rides a wave.\n\nThe key insight: urges are not permanent. They feel overwhelming in the moment but they have a beginning, a peak, and an end. Every urge you have ever had has eventually passed.\n\n## The technique\n\n**Step 1: Notice the urge is present.** Do not immediately try to suppress or satisfy it. Simply name it: there is the urge to bet.\n\n**Step 2: Observe where you feel it in your body.** Tightness in the chest? A specific feeling in your stomach? Restlessness in your hands or legs? Locate the sensation without judging it.\n\n**Step 3: Watch it like weather.** Imagine you are watching a storm from a safe window. The storm is real. You are not in it. Notice: it is getting stronger now. It seems to be at its peak. It is starting to ease.\n\n**Step 4: Breathe through it.** Use slow, extended breathing. Each exhale is a small act of not giving in.\n\n**Step 5: Remind yourself of the timeline.** Most urges peak within 10 to 20 minutes and reduce significantly within 30 minutes.\n\n## What makes this different from suppression\n\nSuppression increases urge intensity. Urge surfing does not ask you to suppress, only to observe. The urge is present. You are watching it. This psychological distance is the skill.\n\n## After the urge passes\n\nNote what happened. Write: how long did the peak last? How did it feel in your body? Over time, this log builds evidence that urges pass and that you can outlast them.",
  'content_sw' => "## Kusafiri kwenye wimbi la hamu ni nini?\n\nBadala ya kupigana na hamu au kutoa kwa, unaiangalia, ukiiona iinuke, ifikilie kilele, na ipite.\n\n## Mbinu\n\n1. Angalia hamu ipo, ipe jina\n2. Angalia inahisi wapi mwilini\n3. Iangalie kama hali ya hewa\n4. Pumua kupitia\n5. Jikumbusha: dakika 10-30",
  'key_takeaways' => json_encode(["Urges are not permanent. Every one has a beginning, peak, and end.", "Urge surfing means observing the urge, not suppressing or acting on it.", "Locate where you feel the urge physically and describe it.", "Watch it like weather from a safe window, present but not consuming you.", "Track your urge surfing: duration, intensity, physical sensation. Evidence builds over time."]),
  'key_takeaways_sw' => json_encode(["Hamu si za kudumu, kila moja ina mwanzo, kilele, na mwisho.", "Kusafiri kwenye wimbi kunamaanisha kuangalia hamu, si kukandamiza wala kutenda.", "Fuatilia kusafiri kwako kwa hamu."]),
],

[
  'title' => 'Rebuilding Your Finances After Gambling',
  'title_sw' => 'Kujenga Tena Fedha Zako Baada ya Kamari',
  'slug' => 'rebuilding-finances-gambling',
  'category' => 'gambling',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 14,
  'thumbnail_emoji' => '💰',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 4,
  'summary' => 'Practical steps to stabilise your finances, pay down gambling debts, and create barriers that protect your money during recovery.',
  'summary_sw' => 'Hatua za vitendo za kuimarisha fedha zako, kulipa madeni ya kamari, na kuunda vizuizi vinavyolinda pesa zako wakati wa kupona.',
  'content' => "## Why financial recovery matters\n\nFinancial damage from gambling is one of the main relapse triggers. Debt creates stress. Stress creates urges. Urges create more debt. Breaking this cycle requires addressing the financial damage directly.\n\n## Step 1: Get a clear picture\n\nWrite down every debt. Include SACCO loans, bank loans, money borrowed from family or friends, mobile loan apps such as Fuliza, Branch, or Tala, and any informal agreements. Add them up. The total is a number, not a judgment. Knowing the actual number is the beginning of addressing it.\n\n## Step 2: Protect your income immediately\n\nGive control of your income to a trusted person for a defined period of at least 3 to 6 months. Options include a trusted family member holding your card, salary paid directly to a joint account, or voluntary self-exclusion from mobile money platforms.\n\n## Step 3: Prioritise debts strategically\n\nFirst: mobile loan apps accruing daily interest. Second: any debt straining a relationship you need. Third: formal debts such as bank loans which typically have structured repayment options. Contact creditors early. Many will negotiate payment plans if you approach them before default.\n\n## Step 4: Create hard barriers to money\n\n- Delete all mobile betting apps permanently\n- Remove card details from betting websites\n- Set mobile money daily limits\n- Avoid carrying large amounts of cash in early recovery\n- Request self-exclusion from betting companies\n\n## Step 5: The small win principle\n\nOnce you have a repayment plan, track every debt paid off however small. Early in recovery, small financial wins matter. Your brain needs evidence that the damage is repairable.",
  'content_sw' => "## Kwa nini kupona kwa fedha ni muhimu\n\nUharibifu wa fedha kutokana na kamari ni moja ya visababishi vikuu vya kurudi.\n\n## Hatua muhimu\n\n1. Pata picha wazi ya deni lako lote\n2. Linda mapato yako mara moja kwa mtu unayemwamini\n3. Toa kipaumbele kwa madeni kwa mkakati\n4. Unda vizuizi vikali vya fedha\n5. Fuatilia malipo madogo ya deni kama ushindi mdogo",
  'key_takeaways' => json_encode(["Financial damage is a major relapse trigger. Address it directly as part of recovery.", "Write down every debt to the exact number. Clarity is the starting point.", "Give control of your income to a trusted person for 3 to 6 months during early recovery.", "Delete apps, remove saved cards, set mobile money limits. Create hard barriers.", "Track every debt payment as a small win. Your brain needs evidence that recovery is real."]),
  'key_takeaways_sw' => json_encode(["Uharibifu wa fedha ni kisababishi kikuu cha kurudi, ushughulikie moja kwa moja.", "Andika kila deni hadi nambari halisi.", "Toa udhibiti wa mapato yako kwa mtu unayemwamini kwa miezi 3-6."]),
],

[
  'title' => 'Telling Someone About Your Gambling',
  'title_sw' => 'Kumwambia Mtu Kuhusu Kamari Yako',
  'slug' => 'telling-someone-gambling',
  'category' => 'gambling',
  'language' => 'en',
  'level' => 'advanced',
  'duration_minutes' => 13,
  'thumbnail_emoji' => '🤝',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 5,
  'summary' => 'Prepare for the disclosure conversation: who to tell, what to say, and how to handle their reaction.',
  'summary_sw' => 'Jiandae kwa mazungumzo ya ufafanuzi: nani wa kumwambia, nini cha kusema, na jinsi ya kushughulikia majibu yao.',
  'content' => "## Why disclosure matters\n\nResearch on addiction recovery consistently shows that people recover better with social support than alone. Secrecy around gambling feeds shame, and shame increases relapse risk. Telling even one person shifts the dynamic in important ways: it creates accountability, allows you to receive practical support, relieves the burden of hiding, and signals to yourself that recovery is real.\n\n## Who to tell first\n\nChoose someone who can hold difficult information without reacting in a way that will make things worse, who has a reason to care about your wellbeing, and who will not immediately tell everyone else without your permission. This does not have to be your closest person. It has to be the right person for this conversation.\n\n## Preparing for the conversation\n\n**Decide what you want from the conversation** before you talk. Are you looking for emotional support? Practical help managing finances? Just to have someone who knows?\n\n**Choose the setting.** Private, unrushed, when the other person is not stressed or distracted. Not by text.\n\n**A framework for what to say:** There is something I have been going through that I need to share with you. I have a problem with gambling. It has caused (brief description of impact). I am getting help and I am committed to stopping. What I need from you is (specific request).\n\n## Handling their reaction\n\n**Anger or hurt** are valid responses if they were affected. Do not defend in the moment. Acknowledge: I understand you are angry. You have reason to be. I am not asking you to trust me right now. I am asking for the chance to show you.\n\n**Shock or minimising** may feel dismissive. Hold your position: it has been affecting my life in ways I did not admit to anyone, including myself.\n\n**Relief** is also common. Many people say their loved ones had suspected something and were relieved to finally know.\n\n## If the first conversation goes badly\n\nThis does not mean disclosure was wrong. It means you may need to try with someone else, or give the person time to process.",
  'content_sw' => "## Kwa nini ufafanuzi unasaidia\n\nUtafiti unaonyesha kwamba watu wanapona vizuri zaidi na msaada wa kijamii kuliko peke yao. Siri kuhusu kamari inailisha aibu, na aibu huongeza hatari ya kurudi.\n\n## Jinsi ya kuandaa mazungumzo\n\nChagua mtu sahihi. Amua unachotaka kutoka kwa mazungumzo. Chagua mazingira ya faragha. Tumia mfumo: tatizo, athari, usaidizi unaohitajika.",
  'key_takeaways' => json_encode(["Secrecy feeds shame and shame increases relapse risk. Disclosure reduces both.", "Choose someone who can hold difficult information, not necessarily your closest person.", "Decide what you want from the conversation before it starts.", "Have a clear framework: the problem, the impact, that you are getting help, and a specific request.", "A difficult first reaction does not mean disclosure was wrong. They may need time."]),
  'key_takeaways_sw' => json_encode(["Siri inailisha aibu, aibu huongeza hatari ya kurudi.", "Chagua mtu anayeweza kushikilia habari ngumu.", "Amua unachotaka kutoka kwa mazungumzo kabla hawajaanza."]),
],

// ─── TRAUMA ────────────────────────────────────────────────────────────────
[
  'title' => 'What Trauma Does to the Body',
  'title_sw' => 'Kilichofanywa na Kiwewe kwa Mwili',
  'slug' => 'what-trauma-does-to-the-body',
  'category' => 'trauma',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 10,
  'thumbnail_emoji' => '💙',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 1,
  'summary' => 'Understand how trauma is stored in the body and nervous system and why your reactions are normal responses to abnormal events.',
  'summary_sw' => 'Elewa jinsi kiwewe kinavyohifadhiwa katika mwili na mfumo wa neva na kwa nini majibu yako ni majibu ya kawaida kwa matukio yasiyo ya kawaida.',
  'content' => "## Your body keeps the score\n\nTrauma is not only a psychological event. It is a physical one. Traumatic experiences change how the nervous system responds to threat, and these changes persist long after the events themselves are over.\n\nThis is not weakness. This is your brain doing exactly what it was designed to do: protect you from a threat it perceived as life-altering.\n\n## What happens during a traumatic event\n\nWhen you experience something overwhelming, your nervous system activates the threat response. This floods you with stress hormones, activates your senses, and focuses all resources on survival.\n\nIf the response cannot complete because you could not fight, flee, or process what happened, the nervous system stays in a partial activation state. This is the beginning of trauma's physical imprint.\n\n## The three common nervous system responses after trauma\n\n**Hyperarousal (fight or flight stuck on):** constant alertness, exaggerated startle response, difficulty sleeping, irritability, physical tension in neck, shoulders, and jaw.\n\n**Hypoarousal (freeze or shutdown):** emotional numbness, feeling disconnected, difficulty feeling emotions, feeling physically heavy or slow, dissociation, difficulty making decisions.\n\n**Oscillation:** many trauma survivors move between both states, over-activated at times and shut down at others. This is disorienting and exhausting.\n\n## Flashbacks and triggers\n\nA flashback is not a memory. It is a re-experiencing. The brain's threat-detection system cannot distinguish between the original event and a sensory cue that resembles it. A smell, a sound, a phrase, or a touch can activate the full trauma response as if the event were happening now.\n\nThis is not a sign that you are going crazy. This is a well-documented neurological process. With support and the right techniques, it can change.\n\n## You responded normally to something abnormal\n\nYour trauma responses are not a sign that something is wrong with you. They are evidence of something terrible that happened to you, and of your nervous system doing its best to keep you safe afterward.",
  'content_sw' => "## Mwili wako unahifadhi alama\n\nKiwewe si tu tukio la kisaikolojia, ni la kimwili. Mabadiliko yanabaki katika mfumo wa neva kwa muda mrefu baada ya matukio kuisha.\n\n## Majibu matatu ya kawaida ya mfumo wa neva baada ya kiwewe\n\n- Hyperarousal: uangalifu wa mara kwa mara, kushindwa kulala\n- Hypoarousal: ganzi la kihisia, kutengana\n- Kutopanda na kushuka: kutorotheka kati ya hali mbili",
  'key_takeaways' => json_encode(["Trauma is stored in the body and nervous system, not just in memory.", "The three common responses are hyperarousal (fight or flight), hypoarousal (freeze), and oscillation between both.", "Flashbacks are re-experiencing events, not just memories. They are triggered by sensory cues.", "Your responses are normal reactions to abnormal events, not signs of weakness.", "With support and the right techniques, trauma's physical imprint can change."]),
  'key_takeaways_sw' => json_encode(["Kiwewe kinahifadhiwa katika mwili na mfumo wa neva, si tu kumbukumbu.", "Majibu matatu ya kawaida: hyperarousal, hypoarousal, na kutopanda na kushuka.", "Majibu yako ni ya kawaida kwa matukio yasiyo ya kawaida."]),
],

[
  'title' => 'Grounding After a Flashback',
  'title_sw' => 'Kuthibitisha Baada ya Mawazo ya Kurudi',
  'slug' => 'grounding-after-flashback',
  'category' => 'trauma',
  'language' => 'en',
  'level' => 'beginner',
  'duration_minutes' => 8,
  'thumbnail_emoji' => '🪨',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 2,
  'summary' => 'Specific grounding techniques for trauma, bringing your nervous system back to the present after a flashback or trigger.',
  'summary_sw' => 'Mbinu maalum za kuthibitisha zilizoundwa kwa ajili ya kiwewe, kurudisha mfumo wako wa neva sasa hivi baada ya mawazo ya kurudi au kisababishi.',
  'content' => "## What is happening during a flashback\n\nDuring a flashback or trauma trigger, your brain has shifted into then. It is responding to the original threat as if it is happening now. Your task is to communicate to your nervous system that you are here, in the present, and that you are safe right now.\n\n## Technique 1: Orientation statements\n\nSpeak out loud or think these present facts: My name is (name). Today is (day). I am in (place). The year is (year). That happened in (year). It is over. I can see (specific thing in the room).\n\nThis seems simple. Under a flashback, it is powerful. You are giving your brain updated, present-moment information.\n\n## Technique 2: Cold water\n\nCold water on the face or wrists activates the mammalian dive reflex, a built-in physiological mechanism that slows the heart rate and reduces arousal. It is one of the fastest ways to bring the nervous system down. Carry a small bottle of cold water when in high-risk situations.\n\n## Technique 3: Bilateral tapping\n\nAlternating bilateral stimulation, tapping alternately on both sides of your body, engages both hemispheres of the brain and helps calm the trauma response. This is the same mechanism used in EMDR therapy.\n\nMethod: Cross your arms over your chest in a butterfly hug and tap alternately on each shoulder, slowly and rhythmically. Or tap alternately on your knees. Continue for 1 to 2 minutes.\n\n## Technique 4: Safe place visualisation\n\nCreate a vivid mental image of a place where you feel completely safe. Build it in detail: what does it look like, what do you hear, what does the temperature feel like? Practise this when calm, so your brain has a clear path to it under stress.\n\n## After the flashback\n\nWhen you are grounded again: acknowledge what happened without judgment, check in with your body, drink water, move gently if possible, and tell your therapist at your next session.",
  'content_sw' => "## Kinachoendelea wakati wa mawazo ya kurudi\n\nWakati wa mawazo ya kurudi, ubongo wako umehamia wakati ule. Kazi yako ni kuwasiliana na mfumo wako wa neva kwamba uko hapa, sasa hivi, na kwamba uko salama.\n\n## Mbinu\n\n1. Tamko la mwelekeo: Jina langu ni, leo ni, niko\n2. Maji baridi usoni au mikononi\n3. Kugonga kwa ulinganifu: butterfly hug\n4. Taswira ya mahali salama",
  'key_takeaways' => json_encode(["During a flashback your brain is in then. Grounding communicates that you are in now and safe.", "Orientation statements give your brain updated present-moment information.", "Cold water activates the dive reflex and rapidly lowers nervous system arousal.", "Bilateral tapping (butterfly hug) engages both brain hemispheres, the same mechanism as EMDR.", "Practise your safe place visualisation when calm so it is accessible under stress."]),
  'key_takeaways_sw' => json_encode(["Wakati wa mawazo ya kurudi, ubongo wako uko wakati ule. Kuthibitisha kunasema uko sasa hivi.", "Tamko la mwelekeo unalipa ubongo wako habari za sasa.", "Maji baridi yanaanzisha dive reflex na kupunguza haraka msisimko."]),
],

[
  'title' => 'The Window of Tolerance',
  'title_sw' => 'Dirisha la Uvumilivu',
  'slug' => 'window-of-tolerance',
  'category' => 'trauma',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 12,
  'thumbnail_emoji' => '🪟',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 3,
  'summary' => 'Learn to recognise when you are inside vs outside your window of tolerance and the skills to return to a regulated state.',
  'summary_sw' => 'Jifunza kutambua unapokuwa ndani au nje ya dirisha lako la uvumilivu na ustadi maalum wa kurudi katika hali ya utulivu.',
  'content' => "## What is the window of tolerance?\n\nThe window of tolerance describes the optimal zone of nervous system arousal where you can function, process information, feel emotions, and engage with others. When trauma is in the system, this window often becomes very narrow. Situations that would be manageable for others push you outside it.\n\n## Above the window: hyperarousal\n\nSigns you are above the window: racing thoughts, intense emotion that feels overwhelming, panic or rage, inability to think clearly, racing heart, shortness of breath, muscle tension.\n\n**What to do: down-regulate.** Extended exhale breathing (4-7-8), cold water on the face, physical grounding by pressing feet into the floor, slow deliberate movement.\n\n## Below the window: hypoarousal\n\nSigns you are below the window: numbness and disconnection, difficulty thinking or speaking, physical heaviness, dissociation and fog, inability to feel emotions.\n\n**What to do: up-regulate.** Vigorous physical movement such as jumping or brisk walking, cold water or fresh air, bilateral tapping or gentle rhythmic movement, engage your senses deliberately with a strong smell or textured surface, connect with another person.\n\n## Widening your window\n\nTrauma therapy aims to widen your window of tolerance through: titration (processing small amounts of trauma material at a time), resource building (developing self-regulation capacity before processing), and pendulation (consciously moving between difficult material and a sense of safety).\n\nThis is why trauma therapy should always be paced by a trained professional. Processing too fast re-traumatises.",
  'content_sw' => "## Dirisha la uvumilivu ni nini?\n\nDirisha la uvumilivu linaelezea eneo bora la msisimko wa mfumo wa neva mahali ambapo unaweza kufanya kazi, kushughulikia hisia, na kushirikiana na wengine.\n\n## Juu ya dirisha: hyperarousal\n\nManeno ya kuwa juu: mawazo yanayokimbia, hisia kali, paniki. Fanya: pumua ndefu, maji baridi, kuthibitisha kimwili.\n\n## Chini ya dirisha: hypoarousal\n\nManeno ya kuwa chini: ganzi, kutengana, uzito wa kimwili. Fanya: harakati kali za kimwili, vichocheo vya hisia, unganika na mtu.",
  'key_takeaways' => json_encode(["The window of tolerance is the zone where you can function. Trauma often narrows it.", "Above the window (hyperarousal): down-regulate with extended breathing, cold water, and physical grounding.", "Below the window (hypoarousal): up-regulate with vigorous movement, sensory engagement, and connection.", "Recognising which zone you are in is the first skill. It tells you what to do.", "Trauma therapy widens the window gradually through titration, resource building, and pendulation."]),
  'key_takeaways_sw' => json_encode(["Dirisha la uvumilivu ni mahali unapoweza kufanya kazi. Kiwewe mara nyingi huifanya nyembamba.", "Juu ya dirisha: punguza kwa kupumua ndefu na maji baridi.", "Chini ya dirisha: ongeza kwa harakati kali na vichocheo vya hisia."]),
],

[
  'title' => 'Processing at Your Own Pace',
  'title_sw' => 'Kushughulikia kwa Kasi Yako Mwenyewe',
  'slug' => 'processing-trauma-your-pace',
  'category' => 'trauma',
  'language' => 'en',
  'level' => 'intermediate',
  'duration_minutes' => 11,
  'thumbnail_emoji' => '🌿',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 4,
  'summary' => 'Understand how trauma processing actually works and why slow, titrated processing with a professional is safer than trying to force resolution.',
  'summary_sw' => 'Elewa jinsi ushughulikiaji wa kiwewe unavyofanya kazi na kwa nini ushughulikiaji wa polepole na mtaalamu ni salama zaidi.',
  'content' => "## The pressure to get over it\n\nPeople who have not experienced trauma often advise: just talk about it and move on, you need to face it, why are you still affected after all this time. This misunderstands how trauma memory works. Trauma is not stored like a normal memory you can retrieve, examine, and file away. It is stored in fragments: disconnected pieces of sensory, emotional, and physical experience that have not been integrated.\n\nPushing too hard, too fast, re-traumatises. It floods the nervous system before it has the resources to process.\n\n## What integration actually means\n\nTrauma processing is not about making the memory disappear or making it not matter. It is about the memory becoming a coherent story: something that happened to you in the past, with a beginning, middle, and end, that can be remembered without re-experiencing.\n\nWhen trauma is processed, you can think about the event without activating the full stress response.\n\n## Titration: the key principle\n\nTitration means approaching the traumatic material in tiny doses: enough to process a fragment, not enough to overwhelm. A good therapist will build your resources first, approach difficult material gradually and briefly, and always return you to a stabilised grounded state within the session.\n\n## What you can do between sessions\n\n- Stabilise first: grounding, breathing, routine\n- Contain when needed: if trauma material is intruding, use containment imagery such as a box, a safe, or a locked drawer, and imagine placing the material there until your next session\n- Notice without engaging: you can notice a thought without following it. There is that memory. Then redirect.\n- Write if it helps: some people find writing fragments helpful to externalise material. Do not write if it destabilises you.\n\n## The non-linear nature of recovery\n\nTrauma recovery is not a straight line. There will be good weeks and harder weeks, steps forward and apparent steps back. This is normal. It does not mean the process is not working. The overall direction matters, not each individual day.",
  'content_sw' => "## Shinikizo la kupita\n\nKusukuma haraka sana kunaumiza tena. Ushughulikiaji wa kiwewe hauhusu kufanya kumbukumbu itoweke. Unahusu kuwa hadithi thabiti ya kitu kilichotokea nawe hapo awali.\n\n## Titration: kanuni muhimu\n\nKuongeza nyenzo ngumu kidogo kidogo. Vya kutosha kushughulikia kipande, si vya kutosha kumlemea.",
  'key_takeaways' => json_encode(["Trauma is stored in fragments, not whole memories. Pushing too fast re-traumatises.", "Processing means the memory becomes a coherent past narrative, not that it disappears.", "Titration: approach traumatic material in tiny doses with a trained professional.", "Between sessions: stabilise first, contain intruding material, notice without engaging.", "Recovery is non-linear. Good weeks and harder weeks are both part of the process."]),
  'key_takeaways_sw' => json_encode(["Kiwewe kinahifadhiwa kwa vipande, kusukuma haraka kunahukumu tena.", "Ushughulikiaji unamaanisha kumbukumbu inakuwa hadithi ya zamani thabiti.", "Kati ya vikao: kwanza thibitisha, halafu zizuie nyenzo zinazoingia."]),
],

[
  'title' => 'Building Safety After Trauma',
  'title_sw' => 'Kujenga Usalama Baada ya Kiwewe',
  'slug' => 'building-safety-after-trauma',
  'category' => 'trauma',
  'language' => 'en',
  'level' => 'advanced',
  'duration_minutes' => 13,
  'thumbnail_emoji' => '🏠',
  'is_premium' => 1,
  'is_published' => 1,
  'order' => 5,
  'summary' => 'Build the internal and external conditions of safety that allow trauma processing to begin and support recovery long-term.',
  'summary_sw' => 'Jenga hali za ndani na za nje za usalama zinazokuruhusu ushughulikiaji wa kiwewe kuanza na kusaidia kupona kwa muda mrefu.',
  'content' => "## Why safety must come first\n\nTrauma processing cannot begin until safety is established. The brain's threat-detection system must believe that the environment is safe before it will allow the processing of old danger.\n\nSafety is both external (your environment and relationships) and internal (your nervous system's sense that you can manage what arises).\n\n## External safety\n\n**Physical safety**: Are you currently in a situation that is physically threatening? Safety from an abusive relationship or a dangerous living situation is a prerequisite for trauma processing.\n\n**Relational safety**: Do you have people around you who will not minimise or re-traumatise you? Even one safe relationship, a friend, a family member, or a therapist, provides a foundation.\n\n**Practical safety**: Basic needs met (shelter, food, income stability) reduce the background stress level that keeps the nervous system in threat mode.\n\n## Internal safety: building your regulation toolkit\n\nInternal safety means having the skills to manage your own nervous system when it activates. This is built through: grounding techniques, breathing regulation, the safe place visualisation, and understanding your window of tolerance and your up-regulate and down-regulate tools.\n\n## The container technique\n\nFor intrusive trauma material, develop a mental container: a strong, sealed image such as a locked safe, a chest at the bottom of the sea, or a box with a combination lock. When intrusive thoughts arise outside of therapy, practise placing them in the container and closing it. This is not denial. It is containment until you have the right support to open it.\n\n## Relationships and safety\n\nPost-trauma, relationships often feel unsafe even with people who are actually trustworthy. Building relational safety is gradual: small disclosures first to observe the response, noticing co-regulation with calm stable people, and not forcing intimacy.\n\n## The long game\n\nRecovery from trauma is not a sprint. Building safety, internally and externally, is not a preliminary stage before the real work begins. It is the work, for many people, for much of the process. A more regulated nervous system, better relationships, and greater self-awareness are themselves the outcome.",
  'content_sw' => "## Kwa nini usalama lazima uje kwanza\n\nUshughulikiaji wa kiwewe hauwezi kuanza mpaka usalama uwekezwe. Mfumo wa kutambua tishio wa ubongo lazima uamini kwamba mazingira ni salama.\n\n## Usalama wa nje\n\nUje katika hali ya usalama wa kimwili, usalama wa uhusiano, na usalama wa msingi.\n\n## Usalama wa ndani: kujenga zana zako\n\nJenga ujuzi wa kudhibiti mfumo wako wa neva kupitia kuthibitisha, kupumua, taswira ya mahali salama, na kuelewa dirisha lako la uvumilivu.",
  'key_takeaways' => json_encode(["Safety must be established before trauma processing can begin, both external and internal.", "External safety: freedom from ongoing threat, at least one safe relationship, basic needs met.", "Internal safety: a regulation toolkit including grounding, breathing, safe place, and window of tolerance tools.", "The container technique: a mental image for holding intrusive material until therapy.", "Building safety is not preliminary to the real work. It is the real work for much of the recovery."]),
  'key_takeaways_sw' => json_encode(["Usalama lazima uwekezwe kabla ya ushughulikiaji wa kiwewe kuanza.", "Usalama wa nje: uhuru kutoka kwa tishio linaloendelea, uhusiano mmoja salama, mahitaji ya msingi.", "Usalama wa ndani: zana za kuthibitisha, kupumua, taswira ya mahali salama."]),
],

]; // end $lessons

$inserted = 0;
$errors = [];
$stmt = $pdo->prepare("
    INSERT INTO lessons
        (title, title_sw, slug, category, language, level, duration_minutes, thumbnail_emoji,
         is_premium, is_published, `order`, summary, summary_sw, content, content_sw,
         key_takeaways, key_takeaways_sw, created_at, updated_at)
    VALUES
        (:title, :title_sw, :slug, :category, :language, :level, :duration_minutes, :thumbnail_emoji,
         :is_premium, :is_published, :order, :summary, :summary_sw, :content, :content_sw,
         :key_takeaways, :key_takeaways_sw, NOW(), NOW())
    ON DUPLICATE KEY UPDATE
        title=VALUES(title), summary=VALUES(summary), content=VALUES(content),
        key_takeaways=VALUES(key_takeaways), is_published=VALUES(is_published),
        updated_at=NOW()
");

foreach ($lessons as $lesson) {
    try {
        $stmt->execute([
            ':title'            => $lesson['title'],
            ':title_sw'         => $lesson['title_sw'],
            ':slug'             => $lesson['slug'],
            ':category'         => $lesson['category'],
            ':language'         => $lesson['language'],
            ':level'            => $lesson['level'],
            ':duration_minutes' => $lesson['duration_minutes'],
            ':thumbnail_emoji'  => $lesson['thumbnail_emoji'],
            ':is_premium'       => $lesson['is_premium'],
            ':is_published'     => $lesson['is_published'],
            ':order'            => $lesson['order'],
            ':summary'          => $lesson['summary'],
            ':summary_sw'       => $lesson['summary_sw'],
            ':content'          => $lesson['content'],
            ':content_sw'       => $lesson['content_sw'],
            ':key_takeaways'    => $lesson['key_takeaways'],
            ':key_takeaways_sw' => $lesson['key_takeaways_sw'],
        ]);
        $inserted++;
    } catch (Exception $e) {
        $errors[] = $lesson['slug'] . ': ' . $e->getMessage();
    }
}

$total = $pdo->query("SELECT COUNT(*) FROM lessons")->fetchColumn();
$byCategory = $pdo->query("SELECT category, COUNT(*) as cnt FROM lessons GROUP BY category ORDER BY category")->fetchAll(PDO::FETCH_ASSOC);
echo json_encode([
    'inserted'    => $inserted,
    'errors'      => $errors,
    'total_now'   => (int)$total,
    'by_category' => $byCategory,
]);
unlink(__FILE__);
