# Generated by Django 4.2.11 on 2026-06-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('assessment', 'Assessment'), ('mood_log', 'Mood Log'), ('craving_log', 'Craving Log')], max_length=20)),
                ('content', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('keywords_detected', models.JSONField(default=list)),
                ('response_action', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crisis_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
