# Generated by Django 4.2.11 on 2026-06-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField()),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EAPTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_employees', models.IntegerField()),
                ('max_employees', models.IntegerField()),
                ('price_kes_annual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sessions_per_employee', models.IntegerField(default=4)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eap_tiers',
            },
        ),
        migrations.CreateModel(
            name='EAPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('employee_limit', models.IntegerField()),
                ('sessions_used', models.IntegerField(default=0)),
                ('sessions_total', models.IntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='corporate.company')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporate.eaptier')),
            ],
            options={
                'db_table': 'eap_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='EAPEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_used', models.IntegerField(default=0)),
                ('sessions_allowed', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('eap_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='corporate.eapsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eap_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eap_employees',
                'unique_together': {('eap_subscription', 'user')},
            },
        ),
    ]
