# Generated by Django 4.2.11 on 2026-06-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('excellent', 'Excellent 😄'), ('good', 'Good 🙂'), ('neutral', 'Neutral 😐'), ('sad', 'Sad 😢'), ('terrible', 'Terrible 😣')], max_length=20)),
                ('mood_score', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('sleep_quality', models.IntegerField()),
                ('triggers', models.TextField(blank=True)),
                ('coping_strategy', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='CravingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(choices=[('alcohol', 'Alcohol'), ('gambling', 'Gambling'), ('tobacco', 'Tobacco'), ('cannabis', 'Cannabis'), ('miraa', 'Miraa'), ('other', 'Other')], max_length=20)),
                ('intensity', models.IntegerField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('trigger', models.TextField(blank=True)),
                ('coping_strategy', models.TextField(blank=True)),
                ('resisted', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craving_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'craving_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='SobrietyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(choices=[('alcohol', 'Alcohol'), ('gambling', 'Gambling'), ('tobacco', 'Tobacco'), ('cannabis', 'Cannabis'), ('miraa', 'Miraa'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_relapses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobriety_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sobriety_trackers',
                'unique_together': {('user', 'substance')},
            },
        ),
    ]
