# Generated by Django 4.2.11 on 2026-06-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('phq9', 'PHQ-9 (Depression)'), ('gad7', 'GAD-7 (Anxiety)'), ('audit', 'AUDIT (Alcohol)'), ('pgsi', 'PGSI (Gambling)'), ('ftnd', 'FTND (Nicotine)')], max_length=10)),
                ('score', models.IntegerField()),
                ('severity', models.CharField(max_length=30)),
                ('interpretation', models.TextField()),
                ('recommendations', models.TextField()),
                ('responses', models.JSONField(default=dict)),
                ('is_crisis_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
