# Generated by Django 4.2.11 on 2026-06-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('depression', 'Depression & Mood'), ('anxiety', 'Anxiety & Stress'), ('alcohol', 'Alcohol Recovery'), ('gambling', 'Gambling Recovery'), ('tobacco', 'Tobacco Cessation'), ('relationships', 'Relationships & Family'), ('wellness', 'General Wellness')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=5)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('summary', models.TextField()),
                ('summary_sw', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('content_sw', models.TextField(blank=True)),
                ('key_takeaways', models.JSONField(default=list)),
                ('key_takeaways_sw', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField(default=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('thumbnail_emoji', models.CharField(default='📚', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_pct', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
